export const types = {
	SELECT_CARD: 'SELECT_CARD',
	MATCH_CARDS: 'MATCH_CARDS',
	RESET_GAME: 'RESET_GAME',
	CREATE_CARDS: 'CREATE_CARDS',
	UPDATE_NUMBER_OF_CARDS: 'UPDATE_NUMBER_OF_CARDS',
	SET_GAME_OVER: 'SET_GAME_OVER',
	START_TIMER: 'START_TIMER',
	TICK_TIMER: 'TICK_TIMER',
	STOP_TIMER: 'STOP_TIMER',
	SET_TIMER: 'SET_TIMER',
	INCREASE_FLIP_COUNT: 'INCREASE_FLIP_COUNT',
	SET_IS_MATCHING: 'SET_IS_MATCHING',
};
